# Generated by Django 3.1.6 on 2021-02-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='display_picture',
        ),
    ]
