# Generated by Django 3.1.6 on 2021-02-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='ct',
        ),
    ]
