# Generated by Django 3.1.6 on 2021-02-14 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0002_remove_details_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='ct',
            field=models.CharField(default=datetime.datetime(2021, 2, 14, 11, 24, 6, 800051, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
